version: 2

models:
  - name: sample2
    description: "Stores user information."
    columns:
      - name: id
        description: "Primary key identifier."
      - name: name
        description: "Name of the user."
      - name: age
        description: "age of the user."