version: 2

models:
  - name: my_table
    description: "Stores user information with timestamps for creation and updates."
    columns:
      - name: id
        description: "Primary key identifier."
      - name: name
        description: "Name of the user."
      - name: email
        description: "Email address of the user."
      - name: created_at
        description: "Timestamp when the record was created."
      - name: updated_at
        description: "Timestamp when the record was last updated."

  - name: sample1
    description: "Sample table containing user and job details."
    columns:
      - name: id
        description: "Primary key identifier."
      - name: name
        description: "Name of the person."
      - name: email
        description: "Email address of the person."
      - name: phone_number
        description: "Phone number of the person."
      - name: job_title
        description: "Job title or role of the person."

  - name: tgt_table
    description: "Target table with user and job information."
    columns:
      - name: id
        description: "Primary key identifier."
      - name: name
        description: "Name of the user."
      - name: email
        description: "Email address of the user."
      - name: phone_number
        description: "Phone number of the user."
      - name: job_title
        description: "Job title or designation."
      - name: created_at