
version: 2

sources:
  - name: public
    tables:
      - name: cio_activity_data
      - name: my_table
      - name: my_table1
      - name: sample1
      - name: sample2
      - name: sample3 
      - name: sample_stream
